version: '3'

services:
  master1:
    image: mysql:5.7.28
    container_name: master1
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./master1.cnf:/etc/mysql/my.cnf
      - ./replicator.sql:/docker-entrypoint-initdb.d/replicator.sql
      - ./master1_data:/var/lib/mysql
  master2:
    image: mysql:5.7.28
    container_name: master2
    restart: "no"
    volumes:
      - ./master2.cnf:/etc/mysql/my.cnf
      - ./replicator.sql:/docker-entrypoint-initdb.d/replicator.sql
      - ./master2_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    depends_on:
      - master1
